Repository snipsco/hermes-protocol, pull requests merged in 2019-07, with the labels that each got.

#129 Fix audio stream MQTT topic decoding
  hermes-mqtt/src/topics.rs
Labels: bug

#131 fix enums path in readme
  platforms/hermes-javascript/README.md
Labels: js

#127 Fix NLU re-exporting symbols issues
  hermes/src/ontology/nlu.rs
Labels: enhancement

#140 js/bump packages
  platforms/hermes-javascript/package-lock.json
  platforms/hermes-javascript/package.json
Labels: js

#141 chore(npm): use ffi package from npm instead of github direct link
  platforms/hermes-javascript/CHANGELOG.md
  platforms/hermes-javascript/package-lock.json
  platforms/hermes-javascript/package.json
Labels: js
